spring.application.name=backend
spring.config.import=classpath:secrets.properties
google.api.key=${GOOGLE_API_KEY}

spring.mongodb.uri=${MONGODB_URI}

jwt.secret=${JWT_SECRET}
jwt.expiration=${EXPIRATION_TIME}